# Helloworld application- just the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koala-deployment
spec:
  selector:
    matchLabels:
      app: koala-arena-app
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: koala-arena-app
    spec:
      containers:
      - name: koala-arena-container
        image: srkodes/flask-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: koala-arena-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: koala-arena-app
